---
abstract: 'a tool to scan your Perl code for its prerequisites'
author:
  - 'Jerome Quelin'
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires:
  File::Temp: 0
  PPI::Document: 0
  Test::More: 0.96
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-PrereqScanner
requires:
  File::Spec::Functions: 0
  FindBin: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  Moose::Role: 0
  PPI: 1.205
  Params::Util: 0
  String::RewritePrefix: 0.005
  Version::Requirements: 0.100630
  namespace::autoclean: 0
  perl: 5.008
resources:
  repository: git://github.com/jquelin/perl-prereqscanner.git
  x_MailingList: http://www.listbox.com/subscribe/?list_id=139292
version: 1.000
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@RJBS/@Basic/GatherDir'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RJBS/@Basic/PruneCruft'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@RJBS/@Basic/ManifestSkip'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RJBS/@Basic/MetaYAML'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::License
      name: '@RJBS/@Basic/License'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@RJBS/@Basic/Readme'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@RJBS/@Basic/ExtraTests'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RJBS/@Basic/ExecDir'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RJBS/@Basic/ShareDir'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RJBS/@Basic/MakeMaker'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RJBS/@Basic/Manifest'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RJBS/@Basic/TestRelease'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RJBS/@Basic/ConfirmRelease'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RJBS/@Basic/UploadToCPAN'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RJBS/AutoPrereqs'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RJBS/Git::NextVersion'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@RJBS/PkgVersion'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RJBS/MetaConfig'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RJBS/MetaJSON'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RJBS/NextRelease'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RJBS/PodSyntaxTests'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@RJBS/Repository'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@RJBS/TestMoreWithSubtests'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@RJBS/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RJBS/@Git/Check'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RJBS/@Git/Commit'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RJBS/@Git/Tag'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RJBS/@Git/Push'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102345
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102345
